### ISSUE TITLE
Data Mixing

### ISSUE THREAD

**Issue by hido710** [Andong-Li-speech/EaBNet#2]
I am amazed by your results!

Actually, after finding out that the pre-trained models were not in the directory, I tried to train the models myself.
But, the data mixing stages are a bit confusing for me.

1. Did you locate the microphone array with parallel to room width or length? or with definitely random angle?
2. Did you locate the sources with 0  to 180 degrees from the center of microphone array? or 0 to 360 degrees (so that the target source and the interference can be placed on the opposite side of the microphone array.)?

Could you please answer this question or share the reference code for mixing the data?

Hope you have a great day, bye!

**Comment by Andong-Li-speech** [comment]
1. The ULA is parallel to room length without rotation in the simulation process. 
2. As we adopt the ULA in the simulation, only 0 to 180 degrees are considered. If you use the circular array in the simulation, you can extend the angle range into [0, 360) or [-180, 180).

**Comment by Andong-Li-speech** [comment]
> I am amazed by your results!
> 
> Actually, after finding out that the pre-trained models were not in the directory, I tried to train the models myself. But, the data mixing stages are a bit confusing for me.
> 
> 1. Did you locate the microphone array with parallel to room width or length? or with definitely random angle?
> 2. Did you locate the sources with 0  to 180 degrees from the center of microphone array? or 0 to 360 degrees (so that the target source and the interference can be placed on the opposite side of the microphone array.)?
> 
> Could you please answer this question or share the reference code for mixing the data?
> 
> Hope you have a great day, bye!

1. The ULA is parallel to room length without rotation in the simulation process. 
2. As we adopt the ULA in the simulation, only 0 to 180 degrees are considered. If you use the circular array in the simulation, you can extend the angle range into [0, 360) or [-180, 180).

**Comment by hido710** [comment]
Thanks for kindly reply. Have a good day!
